### ISSUE TITLE
KeyError: 'animation' when running

### ISSUE THREAD

**Issue by ccgx** [dthoreau/pi-gameframe#15]
Hello,
Id really like to get this running, but just cant. I managed to get de dependencies installed after some fiddling, but now get this error massage:

`Traceback (most recent call last):
  File "gameframe.py", line 101, in <module>
    main(sys.argv)
  File "gameframe.py", line 22, in main
    process_dir(file)
  File "gameframe.py", line 53, in process_dir
    hold_ms = int(config["animation"]["hold"])
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 981, in __getitem__
    raise KeyError(key)
KeyError: 'animation'
`
I downloaded the sd_master.zip (https://github.com/Jerware/GameFrameV2/blob/master/sd/sd_master_v2.zip) from Gameframe and unzipped it directly into the pi-gameframe dir and ran it without any arguments.

Web searching didnt help me find a solution with my non-existing python skills. Maybe you have an idea? Thank you!

**Comment by dthoreau** [comment]
It's been a while since I touched this, I'll look into it in a few days.
Some notes, though:
- It was my first go at Python, it's not ideal code.
- The hardware for this is no longer sold, it may differ on other hardware.
- I started another project (un-pushed as yet) to put a RESTful API on the interface, but it was less than ideal. I may come back to it and improve this.

**Comment by ccgx** [comment]
Thanks for the reaction. Im aware that its no longer sold, but Im sure that Im not the only one using the ubercorn as gameframe. Currently Im operating it with a extended sample script from pimoroni, but having the alternative of using the more capable gameframe logic would be great.
So thanks again, I'll wait for an update (:
